# Docker compose file to start a multi node local test network.
#
# # Nodes
#
# - Validator node A
# - Validator node B
# - Light client C
#
# # Auxiliary nodes
#
# - Prometheus monitoring each node.
# - Grafana pointed at the Prometheus node, configured with all dashboards.
#
# # Usage
#
# 1. Build `target/release/substrate` binary: `cargo build --release`
# 2. Start networks and containers:
#    `sudo docker-compose -f .maintain/sentry-node/docker-compose.yml up`
# 3. Connect to nodes:
#   - validator-a: localhost:9944
#   - validator-b: localhost:9945
#   - light-c: localhost:9946
#   - via polkadot.js/apps: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2Flocalhost%3A<NODE_PORT>#/explorer
#   - grafana: localhost:3001
#   - prometheus: localhost:9090


version: "3.7"
services:

  node1:
    env_file: env_file
    image: btwiuse/nftmart:beta
    tty: true
    entrypoint: [ "bash", "--rcfile", "/entrypoint.rc", "-ic" ]
    network_mode: host
    volumes:
    - ./entrypoint.rc:/entrypoint.rc
    - ./state/node1:/data/state/node1
    command: node1
    container_name: node1

  node2:
    env_file: env_file
    image: btwiuse/nftmart:beta
    tty: true
    entrypoint: [ "bash", "--rcfile", "/entrypoint.rc", "-ic" ]
    network_mode: host
    volumes:
    - ./entrypoint.rc:/entrypoint.rc
    - ./state/node2:/data/state/node2
    command: node2
    container_name: node2
