global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'substrate-nodes'
    static_configs:
      - targets:
      # - 'node1.127.0.0.1.xip.io:9615'
      # - 127.0.0.1:9615
        - node1:9615
        labels:
          network: dev
      - targets:
      # - 'node1.127.0.0.1.xip.io:9616'
      # - 127.0.0.1:9616
        - node2:9616
        labels:
          network: dev
    # - targets: ['light-c:9615']
    #   labels:
    #     network: dev
